version: '3'
services:
  films:
    container_name: films
    build:
      context: config
      dockerfile: Dockerfile
    command: sh -c ""
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: "postgres:9.6.1"
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'admin'
    volumes:
      - ./data_volumes/postgres:/var/lib/postgresql/data
    restart: always